#db.url=jdbc:postgresql://nitron.space:5432/destination_db
db.url=jdbc:postgresql://localhost:5432/destination_db
db.username=app_admin
db.password=Root@Passord123
db.driver=org.postgresql.Driver

#kafka.bootstrap.servers=nitron.space:39092
kafka.bootstrap.servers=localhost:29092
kafka.group.id=etl-group
kafka.topic=etl-topic
kafka.auto.offset.reset=earliest
