db.url=jdbc:postgresql://nitron.space:5432/destination_db
db.username=admin
db.password=password
db.driver=org.postgresql.Driver

kafka.bootstrap.servers=nitron.space:39092
kafka.group.id=etl-group
kafka.topic=etl-topic
kafka.auto.offset.reset=earliest
