{
 "title": "ETL Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "🔵 THROUGHPUT METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Records Consumed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "increase(etl_kafka_records_total[5m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput per Partition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "rate(etl_kafka_partition_records_total[$__rate_interval])",
       "legendFormat": "{{partition}}"
      }
     ]
    },
    {
     "title": "Throughput per Thread",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(etl_kafka_thread_records_total[1m])",
       "legendFormat": "{{thread}}"
      }
     ]
    },
    {
     "title": "Kafka Bytes Consumed per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(etl_kafka_bytes_total[1m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput total (msgs processed p/ seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(etl_processed_total[1m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "🟣 LATENCY METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Listener Processing Time (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(etl_kafka_processing_ns_sum / etl_kafka_processing_ns_count) / 1e6\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database Execution Time (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(etl_db_ns_sum / etl_db_ns_count) / 1e6\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "End-to-End Latency (Kafka → Transform → DB) (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(etl_end_to_end_ns_sum / etl_end_to_end_ns_count) / 1e6\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transform Time (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(etl_transform_ns_sum / etl_transform_ns_count) / 1e6\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "🟠 PERCENTILES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "P95 End-to-End Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(etl_end_to_end_ns_bucket[5m])) by (le)\r\n) / 1e6",
       "legendFormat": "P95 (5%)"
      }
     ]
    },
    {
     "title": "P99 End-to-End Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(rate(etl_end_to_end_ns_bucket[5m])) by (le)\r\n) / 1e6",
       "legendFormat": "P99 (1%)"
      }
     ]
    }
   ]
  },
  {
   "title": "🔴 RELIABILITY / ERROR METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "ETL Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "increase(etl_errors_total[5m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Slow Database Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "increase(etl_db_slow_queries_total[5m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}